## Generates a GDScript file of tag constants for IDE autocomplete.
##
## Turns the registry's StringName tags into `const Status_Stunned: StringName =
## &"Status.Stunned"`, so gameplay code names a tag through a symbol the editor
## can complete and a rename can follow, instead of retyping the literal.
##
## @meta_addon: GodotGAS, Arhalies fork
## @meta_author: YulRun (https://YulRun.Dev), Arhalies fork
## @meta_license: MIT

@tool
@icon("res://addons/GodotGAS/icons/godot_gas_asc.svg")
class_name GameplayTagGenerator extends RefCounted

## The line printed once a generated file is written.
const GENERATED_REPORT: String = "GodotGAS: generated %s with %d constants."

## Anything outside this set becomes an underscore in a generated identifier.
const IDENTIFIER_PATTERN: String = "[^a-zA-Z0-9_]"

const SEGMENT_SEPARATOR: String = "."
const IDENTIFIER_SEPARATOR: String = "_"

## The header every generated file carries, so nobody edits one by hand.
const HEADER_LINES: Array[String] = [
	"## AUTO-GENERATED BY GodotGAS. DO NOT EDIT MANUALLY.",
	"##",
	"## StringName references to the project's gameplay tags.",
	"##",
	"## @meta_addon: GodotGAS, Arhalies fork",
	GDScriptSource.LICENSE_DOC_LINE,
	"",
	GDScriptSource.TOOL_ANNOTATION,
	"class_name GameplayTags",
	"",
]


#region Code Generation
## Write the constants file for these tags.
static func generate_tags_file(tags: Array[StringName]) -> void:
	var output_path: String = GodotGasProjectSettings.get_generated_tag_script_path()
	var file: FileAccess = FileAccess.open(output_path, FileAccess.WRITE)
	if file == null:
		printerr("GodotGAS: could not open the tag output path: " + output_path)
		return

	for line: String in HEADER_LINES:
		file.store_line(line)

	for tag: StringName in tags:
		file.store_line(constant_line(tag))

	file.close()
	print(GENERATED_REPORT % [output_path, tags.size()])


## One `const NAME: StringName = &"Tag"` line.
static func constant_line(tag: StringName) -> String:
	var tag_string: String = String(tag)
	var constant_name: String = sanitize_identifier(
		tag_string.replace(SEGMENT_SEPARATOR, IDENTIFIER_SEPARATOR)
	)
	return "const " + constant_name + ": StringName = &\"" + tag_string + "\""
#endregion


#region Helpers
## Make a string safe to use as a GDScript identifier.
##
## A leading digit is prefixed rather than dropped: dropping it would collapse
## `1Fire` and `Fire` into one constant, and the second definition would
## silently win.
static func sanitize_identifier(raw: String) -> String:
	var regex: RegEx = RegEx.new()
	regex.compile(IDENTIFIER_PATTERN)
	var sanitized: String = regex.sub(raw, IDENTIFIER_SEPARATOR, true)

	if not sanitized.is_empty() and sanitized[0].is_valid_int():
		sanitized = IDENTIFIER_SEPARATOR + sanitized

	return sanitized
#endregion
