## Generates a GDScript file of tag constants for IDE autocomplete.
##
## Turns the registry's StringName tags into `const Status_Stunned: StringName =
## &"Status.Stunned"`, so gameplay code names a tag through a symbol the editor
## can complete and a rename can follow, instead of retyping the literal.
##
## @meta_addon: GAS_Engine
## @meta_author: MaliciaInc
## @meta_license: GAS_Engine Community Use License 1.0

@tool
@icon("res://addons/GAS_Engine/icons/gas_engine_asc.svg")
class_name GameplayTagGenerator extends RefCounted

## The line printed once a generated file is written.
const CONST_WORD: String = "const "
const TAG_OPEN: String = '&"'
const TAG_CLOSE: String = '"'
const NEWLINE: String = "
"

const GENERATED_REPORT: String = "GAS_Engine: generated %s with %d constants."

## Said out loud rather than printed: a designer who added a tag and got no
## constant needs to know, and stderr scrolls past.
const WRITE_FAILED: String = "GAS_Engine: could not write the generated tag script to %s."

## Anything outside this set becomes an underscore in a generated identifier.
const IDENTIFIER_PATTERN: String = "[^a-zA-Z0-9_]"

const SEGMENT_SEPARATOR: String = "."
const LINE_BREAK: String = "\n"
const IDENTIFIER_SEPARATOR: String = "_"

## The header every generated file carries, so nobody edits one by hand.
const HEADER_LINES: Array[String] = [
	"## AUTO-GENERATED BY GAS_Engine. DO NOT EDIT MANUALLY.",
	"##",
	"## StringName references to the project's gameplay tags.",
	"##",
	"## @meta_addon: GAS_Engine",
	GDScriptSource.LICENSE_DOC_LINE,
	"",
	GDScriptSource.TOOL_ANNOTATION,
	"class_name GameplayTags",
	"",
]


#region Code Generation
## The whole generated file as text, from these tags and nothing else.
##
## Pure and deterministic: the same tags produce the same bytes. That is what
## lets a test compare the tracked file against this without an editor, and it
## is why the writer below produces nothing of its own - two places building
## the same text would eventually build it differently.
static func render_tags_source(tags: Array[StringName]) -> String:
	var lines: Array[String] = []
	lines.assign(HEADER_LINES)
	for tag: StringName in tags:
		lines.append(constant_line(tag))
	return LINE_BREAK.join(lines) + LINE_BREAK


## Write the constants file for these tags.
## The tags this project has, read back out of the file that holds them.
##
## The file used to be a copy of a registry resource, which meant two places a
## tag could live and one of them going stale the moment somebody edited the
## other by hand. It is the registry now: written here, read here, and nothing
## else to keep in step with it.
##
## Read as text rather than loaded. The file declares a global `class_name`, so
## loading a second copy of it - which is exactly what a test does, and what any
## caller pointing at another path would do - collides with the one Godot has
## already registered. Reading also costs no compile, and the format being
## parsed is the one rendered eight lines further down.
static func tags_in_file() -> Array[StringName]:
	var found: Array[StringName] = []
	var path: String = GASEngineProjectSettings.get_generated_tag_script_path()
	if not FileAccess.file_exists(path):
		return found

	for line: String in FileAccess.get_file_as_string(path).split(NEWLINE):
		var tag: String = _tag_named_in(line.strip_edges())
		if not tag.is_empty():
			found.append(StringName(tag))
	# Not sorted here. The file was written in order and reading it back must
	# hand that order over unchanged - and `Array[StringName].sort()` would not
	# even be the right order to impose: StringName compares by its own internal
	# ordering, not alphabetically, so sorting here silently reshuffled the
	# project's tags on the first read.
	return found


## The tag a constant line names, or nothing when the line names none.
static func _tag_named_in(line: String) -> String:
	if not line.begins_with(CONST_WORD):
		return ""
	var opened: int = line.find(TAG_OPEN)
	var closed: int = line.rfind(TAG_CLOSE)
	if opened < 0 or closed <= opened + TAG_OPEN.length() - 1:
		return ""
	var from: int = opened + TAG_OPEN.length()
	return line.substr(from, closed - from)


static func generate_tags_file(tags: Array[StringName]) -> bool:
	var output_path: String = GASEngineProjectSettings.get_generated_tag_script_path()
	# The directory does not exist in a fresh checkout. Creating it is the
	# difference between generating the constants and reporting that it could
	# not open a path nobody asked it to invent.
	DirAccess.make_dir_recursive_absolute(
		ProjectSettings.globalize_path(output_path.get_base_dir())
	)
	var file: FileAccess = FileAccess.open(output_path, FileAccess.WRITE)
	if file == null:
		push_error(WRITE_FAILED % output_path)
		return false

	file.store_string(render_tags_source(tags))
	var write_error: Error = file.get_error()
	file.close()
	if write_error != OK:
		push_error(WRITE_FAILED % output_path)
		return false
	print(GENERATED_REPORT % [output_path, tags.size()])
	return true


## One `const NAME: StringName = &"Tag"` line.
static func constant_line(tag: StringName) -> String:
	var tag_string: String = String(tag)
	var constant_name: String = sanitize_identifier(
		tag_string.replace(SEGMENT_SEPARATOR, IDENTIFIER_SEPARATOR)
	)
	return "const " + constant_name + ": StringName = &\"" + tag_string + "\""
#endregion


#region Helpers
## Make a string safe to use as a GDScript identifier.
##
## A leading digit is prefixed rather than dropped: dropping it would collapse
## `1Fire` and `Fire` into one constant, and the second definition would
## silently win.
static func sanitize_identifier(raw: String) -> String:
	var regex: RegEx = RegEx.new()
	regex.compile(IDENTIFIER_PATTERN)
	var sanitized: String = regex.sub(raw, IDENTIFIER_SEPARATOR, true)

	if not sanitized.is_empty() and sanitized[0].is_valid_int():
		sanitized = IDENTIFIER_SEPARATOR + sanitized

	return sanitized
#endregion
