## Turns a drafted attribute set into GDScript source.
##
## Pure: it takes names and numbers and returns text. No file access, no
## dialogs, no editor calls, so what it emits can be asserted directly in a test
## instead of being inspected by opening the generated file.
##
## The emitted code is kept correct against the current hooks. It used to
## write `pre_attribute_change(attribute_name: String, ...)` - the hook now takes
## a StringName - it never wrote `pre_attribute_base_change` at all, and its
## dependency handling called `asc._apply_attribute_change()`, a method the ASC
## no longer has. A generator that emits code which does not compile is worse
## than no generator: it produces a file that looks authored.
##
## @meta_addon: GAS_Engine
## @meta_license: GAS_Engine Community Use License 1.0

@tool
class_name AttributeSetScriptWriter extends RefCounted

const MAX_PREFIX: String = "max_"
const MIN_PREFIX: String = "min_"
const INDENT: String = "\t"
const NEWLINE: String = "\n"

## The parameter every emitted hook matches on, and the prefix GDScript
## wants on a parameter nothing reads. A generated file lands in the game's
## own source tree under the game's own warning settings: a project that
## raises `unused_parameter` to Error - an ordinary thing to do, and what
## this addon does to itself for eight other warnings - would refuse to
## parse a hook carrying one.
const SUBJECT: String = "attribute_name"
const MOVED_VALUE: String = "new_value"
const UNUSED: String = "_"

## The line both hooks open their body with, written whole rather than
## composed from SUBJECT. `"match "` on its own is a bare keyword literal,
## and the gates already see that word in the tooling, so composing it here
## would make the pair a repeat of a word two unrelated files use for two
## unrelated things. The emitted signature carries the subject the same way,
## as a whole line with one hole in it.
const MATCH_SUBJECT_LINE: String = "match attribute_name:"


## One drafted attribute: its name and its starting base value.
class Attribute extends RefCounted:
	var name: String = ""
	var default_value: float = 0.0

	static func of(attribute_name: String, value: float) -> Attribute:
		var attribute: Attribute = Attribute.new()
		attribute.name = attribute_name
		attribute.default_value = value
		return attribute


## The file name a set compiles to.
static func file_name_for(set_name: String) -> String:
	return set_name.to_snake_case() + "_attribute_set.gd"


## The complete source of one generated attribute set.
static func write(set_name: String, attributes: Array[Attribute]) -> String:
	var parts: PackedStringArray = PackedStringArray()
	parts.append(_header(set_name))
	parts.append(_declarations(attributes))
	parts.append(_base_clamp(attributes))
	parts.append(_current_clamp(attributes))
	parts.append(_dependency_hook(attributes))
	return NEWLINE.join(parts)


static func _header(set_name: String) -> String:
	return (
		"## Attribute module: " + set_name + NEWLINE
		+ "##" + NEWLINE
		+ "## Generated by the GAS_Engine dashboard. Edits are overwritten on the next" + NEWLINE
		+ "## generation; change the draft instead." + NEWLINE
		+ "##" + NEWLINE
		+ GDScriptSource.LICENSE_DOC_LINE + NEWLINE
		+ NEWLINE
		+ GDScriptSource.TOOL_ANNOTATION + NEWLINE
		+ "class_name " + set_name + "AttributeSet extends AttributeSet" + NEWLINE
	)


static func _declarations(attributes: Array[Attribute]) -> String:
	var lines: PackedStringArray = PackedStringArray()
	for attribute: Attribute in attributes:
		lines.append(
			"@export var " + attribute.name + ": AttributeData = AttributeData.new("
			+ str(attribute.default_value) + ")"
		)
	return NEWLINE.join(lines) + NEWLINE


## Guard the durable value. This hook did not exist in the generated output
## before, which is how a character could reach `health.base = -400`.
static func _base_clamp(attributes: Array[Attribute]) -> String:
	return _clamp_function(
		attributes,
		"## Guard the durable value.",
		"func pre_attribute_base_change(%s: StringName, proposed_base_value: float) -> float:",
		"proposed_base_value"
	)


static func _current_clamp(attributes: Array[Attribute]) -> String:
	return _clamp_function(
		attributes,
		"## Guard the derived value.",
		"func pre_attribute_change(%s: StringName, proposed_current_value: float) -> float:",
		"proposed_current_value"
	)


## Emit a clamp that bounds every attribute which has a matching `max_` sibling.
##
## With nothing to bound, this used to emit `match attribute_name:` over a
## lone `_: pass` - a branch that decides nothing, present only so the
## parameter would count as read. The bare pass-through says the same thing
## without a statement that never runs, and without the parameter a project
## holding itself to `unused_parameter` would refuse to compile.
static func _clamp_function(
	attributes: Array[Attribute], doc: String, signature: String, value_name: String
) -> String:
	var branches: PackedStringArray = _clamp_branches(_names_of(attributes), value_name)
	var subject: String = SUBJECT if not branches.is_empty() else UNUSED + SUBJECT

	var lines: PackedStringArray = PackedStringArray()
	lines.append(doc)
	lines.append(signature % subject)
	if not branches.is_empty():
		lines.append(INDENT + MATCH_SUBJECT_LINE)
		lines.append_array(branches)
		lines.append("")
	lines.append(INDENT + "return " + value_name)
	return NEWLINE.join(lines) + NEWLINE


## One `match` case per bounded attribute, and nothing at all when none is.
static func _clamp_branches(names: PackedStringArray, value_name: String) -> PackedStringArray:
	var branches: PackedStringArray = PackedStringArray()
	for name: String in names:
		if _is_bound_name(name):
			continue
		var upper: String = MAX_PREFIX + name
		if not names.has(upper):
			continue
		var lower: String = MIN_PREFIX + name
		var floor_expression: String = lower + ".current_value" if names.has(lower) else "0.0"
		branches.append(INDENT.repeat(2) + "&\"" + name + "\":")
		branches.append(
			INDENT.repeat(3) + "return clampf(" + value_name + ", " + floor_expression
			+ ", " + upper + ".current_value)"
		)
	return branches


## React to a bound moving. Both base and current are trimmed: trimming only
## the current would leave the durable value holding more than the bound
## allows, and it would reappear the moment the bound rose again.
##
## With no bound to react to, every parameter of the emitted hook is unread.
## They were named as if they were used, so a set drafted with no `max_` or
## `min_` sibling anywhere - the ordinary shape of a first draft - generated
## a file that raises UNUSED_PARAMETER, and one that a project raising that
## warning to Error would not compile at all.
static func _dependency_hook(attributes: Array[Attribute]) -> String:
	var branches: PackedStringArray = _dependency_branches(_names_of(attributes))
	var used: bool = not branches.is_empty()
	var subject: String = SUBJECT if used else UNUSED + SUBJECT
	var moved: String = MOVED_VALUE if used else UNUSED + MOVED_VALUE

	var lines: PackedStringArray = PackedStringArray()
	lines.append("## React to a bound changing.")
	lines.append(
		"func post_attribute_change(" + NEWLINE
		+ INDENT + "_asc: Node, " + subject + ": StringName, _old_value: float, "
		+ moved + ": float" + NEWLINE + ") -> void:"
	)
	if not used:
		lines.append(INDENT + "pass")
		return NEWLINE.join(lines) + NEWLINE

	lines.append(INDENT + MATCH_SUBJECT_LINE)
	lines.append_array(branches)
	return NEWLINE.join(lines) + NEWLINE


## One `match` case per bound, trimming the attribute it bounds.
static func _dependency_branches(names: PackedStringArray) -> PackedStringArray:
	var branches: PackedStringArray = PackedStringArray()
	for name: String in names:
		if _is_bound_name(name):
			continue
		if names.has(MAX_PREFIX + name):
			branches.append(INDENT.repeat(2) + "&\"" + MAX_PREFIX + name + "\":")
			branches.append(INDENT.repeat(3) + name + ".base_value = minf(" + name + ".base_value, new_value)")
			branches.append(INDENT.repeat(3) + name + ".current_value = minf(" + name + ".current_value, new_value)")
		if names.has(MIN_PREFIX + name):
			branches.append(INDENT.repeat(2) + "&\"" + MIN_PREFIX + name + "\":")
			branches.append(INDENT.repeat(3) + name + ".base_value = maxf(" + name + ".base_value, new_value)")
			branches.append(INDENT.repeat(3) + name + ".current_value = maxf(" + name + ".current_value, new_value)")
	return branches


static func _names_of(attributes: Array[Attribute]) -> PackedStringArray:
	var names: PackedStringArray = PackedStringArray()
	for attribute: Attribute in attributes:
		names.append(attribute.name)
	return names


## Whether a name is itself a bound rather than a bounded value.
static func _is_bound_name(name: String) -> bool:
	var lowered: String = name.to_lower()
	return lowered.begins_with(MAX_PREFIX) or lowered.begins_with(MIN_PREFIX)
