## Turns a drafted attribute set into GDScript source.
##
## Pure: it takes names and numbers and returns text. No file access, no
## dialogs, no editor calls, so what it emits can be asserted directly in a test
## instead of being inspected by opening the generated file.
##
## The emitted code is kept correct against the current hooks. It used to
## write `pre_attribute_change(attribute_name: String, ...)` - the hook now takes
## a StringName - it never wrote `pre_attribute_base_change` at all, and its
## dependency handling called `asc._apply_attribute_change()`, a method the ASC
## no longer has. A generator that emits code which does not compile is worse
## than no generator: it produces a file that looks authored.
##
## @meta_addon: GAS_Engine
## @meta_license: MIT

@tool
class_name AttributeSetScriptWriter extends RefCounted

const MAX_PREFIX: String = "max_"
const MIN_PREFIX: String = "min_"
const INDENT: String = "\t"
const NEWLINE: String = "\n"


## One drafted attribute: its name and its starting base value.
class Attribute extends RefCounted:
	var name: String = ""
	var default_value: float = 0.0

	static func of(attribute_name: String, value: float) -> Attribute:
		var attribute: Attribute = Attribute.new()
		attribute.name = attribute_name
		attribute.default_value = value
		return attribute


## The file name a set compiles to.
static func file_name_for(set_name: String) -> String:
	return set_name.to_snake_case() + "_attribute_set.gd"


## The complete source of one generated attribute set.
static func write(set_name: String, attributes: Array[Attribute]) -> String:
	var parts: PackedStringArray = PackedStringArray()
	parts.append(_header(set_name))
	parts.append(_declarations(attributes))
	parts.append(_base_clamp(attributes))
	parts.append(_current_clamp(attributes))
	parts.append(_dependency_hook(attributes))
	return NEWLINE.join(parts)


static func _header(set_name: String) -> String:
	return (
		"## Attribute module: " + set_name + NEWLINE
		+ "##" + NEWLINE
		+ "## Generated by the GAS_Engine dashboard. Edits are overwritten on the next" + NEWLINE
		+ "## generation; change the draft instead." + NEWLINE
		+ "##" + NEWLINE
		+ GDScriptSource.LICENSE_DOC_LINE + NEWLINE
		+ NEWLINE
		+ GDScriptSource.TOOL_ANNOTATION + NEWLINE
		+ "class_name " + set_name + "AttributeSet extends AttributeSet" + NEWLINE
	)


static func _declarations(attributes: Array[Attribute]) -> String:
	var lines: PackedStringArray = PackedStringArray()
	for attribute: Attribute in attributes:
		lines.append(
			"@export var " + attribute.name + ": AttributeData = AttributeData.new("
			+ str(attribute.default_value) + ")"
		)
	return NEWLINE.join(lines) + NEWLINE


## Guard the durable value. This hook did not exist in the generated output
## before, which is how a character could reach `health.base = -400`.
static func _base_clamp(attributes: Array[Attribute]) -> String:
	return _clamp_function(
		attributes,
		"## Guard the durable value.",
		"func pre_attribute_base_change(attribute_name: StringName, proposed_base_value: float) -> float:",
		"proposed_base_value"
	)


static func _current_clamp(attributes: Array[Attribute]) -> String:
	return _clamp_function(
		attributes,
		"## Guard the derived value.",
		"func pre_attribute_change(attribute_name: StringName, proposed_current_value: float) -> float:",
		"proposed_current_value"
	)


## Emit a clamp that bounds every attribute which has a matching `max_` sibling.
static func _clamp_function(
	attributes: Array[Attribute], doc: String, signature: String, value_name: String
) -> String:
	var names: PackedStringArray = _names_of(attributes)
	var lines: PackedStringArray = PackedStringArray()
	lines.append(doc)
	lines.append(signature)
	lines.append(INDENT + "match attribute_name:")

	var matched: bool = false
	for name: String in names:
		if _is_bound_name(name):
			continue
		var upper: String = MAX_PREFIX + name
		if not names.has(upper):
			continue
		var lower: String = MIN_PREFIX + name
		var floor_expression: String = lower + ".current_value" if names.has(lower) else "0.0"
		lines.append(INDENT.repeat(2) + "&\"" + name + "\":")
		lines.append(
			INDENT.repeat(3) + "return clampf(" + value_name + ", " + floor_expression
			+ ", " + upper + ".current_value)"
		)
		matched = true

	if not matched:
		lines.append(INDENT.repeat(2) + "_:")
		lines.append(INDENT.repeat(3) + "pass")

	lines.append("")
	lines.append(INDENT + "return " + value_name)
	return NEWLINE.join(lines) + NEWLINE


## React to a bound moving. Both base and current are trimmed: trimming only the
## current would leave the durable value holding more than the bound allows, and
## it would reappear the moment the bound rose again.
static func _dependency_hook(attributes: Array[Attribute]) -> String:
	var names: PackedStringArray = _names_of(attributes)
	var lines: PackedStringArray = PackedStringArray()
	lines.append("## React to a bound changing.")
	lines.append(
		"func post_attribute_change(" + NEWLINE
		+ INDENT + "_asc: Node, attribute_name: StringName, _old_value: float, new_value: float"
		+ NEWLINE + ") -> void:"
	)
	lines.append(INDENT + "match attribute_name:")

	var matched: bool = false
	for name: String in names:
		if _is_bound_name(name):
			continue
		if names.has(MAX_PREFIX + name):
			lines.append(INDENT.repeat(2) + "&\"" + MAX_PREFIX + name + "\":")
			lines.append(INDENT.repeat(3) + name + ".base_value = minf(" + name + ".base_value, new_value)")
			lines.append(INDENT.repeat(3) + name + ".current_value = minf(" + name + ".current_value, new_value)")
			matched = true
		if names.has(MIN_PREFIX + name):
			lines.append(INDENT.repeat(2) + "&\"" + MIN_PREFIX + name + "\":")
			lines.append(INDENT.repeat(3) + name + ".base_value = maxf(" + name + ".base_value, new_value)")
			lines.append(INDENT.repeat(3) + name + ".current_value = maxf(" + name + ".current_value, new_value)")
			matched = true

	if not matched:
		lines.append(INDENT.repeat(2) + "_:")
		lines.append(INDENT.repeat(3) + "pass")

	return NEWLINE.join(lines) + NEWLINE


static func _names_of(attributes: Array[Attribute]) -> PackedStringArray:
	var names: PackedStringArray = PackedStringArray()
	for attribute: Attribute in attributes:
		names.append(attribute.name)
	return names


## Whether a name is itself a bound rather than a bounded value.
static func _is_bound_name(name: String) -> bool:
	var lowered: String = name.to_lower()
	return lowered.begins_with(MAX_PREFIX) or lowered.begins_with(MIN_PREFIX)
