#!/usr/bin/env python3
"""Write and verify the policy seal over the gates and their configuration.

The seal exists so that a change to a gate or to the policy it enforces cannot
pass unnoticed: verification stops at POLICY_DRIFT before any gate has a chance
to report a comforting green.

Its file list used to be maintained by hand, which left the hole this file
closes. A hand-written list can only catch a *changed* file. A new one - a new
module under tooling/gates/lib, a new tool under tooling/ - was simply absent
from the seal, and every hash in it still matched. The seal would verify while
covering less than it claimed, which is the failure it was built to prevent.

So the list is derived from the globs it describes, and checking runs both ways:
every sealed file must still hash the same, and every file the globs reach must
be in the seal.

    python tooling/seal_policy.py            # check; what verification runs
    python tooling/seal_policy.py write      # reseal, after an authorised change

Exit 0 when the seal holds, 1 when it does not, 2 on a usage error.
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from _gatelib import gate_io  # noqa: E402

SEAL_PATH = Path("artifacts/gates/T0/final-policy-hashes.txt")

#: Checking is what the verification chain runs, so it is the default and
#: the caller names no action at all.
CHECK, WRITE = "check", "write"

#: What the seal covers. Each gate's runtime, the shared library, the runner,
#: the policy files, and the tools that can change how any of them behave.
#: `lib/*.py` rather than `lib/*`, which would admit a stale .pyc.
SEALED_GLOBS = (
    "tooling/" + gate_io.CONFIG_FILENAME,
    "tooling/*.py",
    "tooling/verify.ps1",
    "tooling/gates/*.py",
    "tooling/gates/*.json",
    "tooling/gates/lib/*.py",
)

SEPARATOR = "  "
COMMENT = "#"
DRIFT = "POLICY_DRIFT"


def sealed_files(root: Path) -> list[str]:
    """Every path the globs reach, repository-relative and sorted."""
    found: set[str] = set()
    for pattern in SEALED_GLOBS:
        for path in root.glob(pattern):
            if path.is_file():
                found.add(path.relative_to(root).as_posix())
    return sorted(found)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_seal(path: Path) -> tuple[dict[str, str], list[str]]:
    """The seal's hashes by path, and its comment header verbatim."""
    hashes: dict[str, str] = {}
    header: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if line.startswith(COMMENT):
            header.append(line)
            continue
        parts = line.split(SEPARATOR, 1)
        if len(parts) != 2:
            raise ValueError("unreadable seal line: " + line)
        hashes[parts[1].strip()] = parts[0].strip().lower()
    return hashes, header


def current_commit(root: Path) -> str:
    done = subprocess.run(
        [gate_io.GIT_EXECUTABLE, "-C", str(root), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=False,
    )
    return done.stdout.strip() if done.returncode == 0 else "no commit yet"


def check(root: Path, reasons: list[str]) -> bool:
    """True when the seal covers exactly what it should, unchanged."""
    path = root / SEAL_PATH
    if not path.is_file():
        reasons.append("seal file is missing at " + SEAL_PATH.as_posix())
        return False

    hashes, _ = read_seal(path)
    present = set(sealed_files(root))

    for relative, expected in sorted(hashes.items()):
        full = root / relative
        if not full.is_file():
            reasons.append(relative + " (sealed, now missing)")
        elif digest(full) != expected:
            reasons.append(relative + " (changed)")

    # The direction a hand-maintained list could not check.
    for relative in sorted(present - set(hashes)):
        reasons.append(relative + " (reached by the sealed globs, absent from the seal)")

    return not reasons


def write(root: Path, note: str) -> int:
    path = root / SEAL_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    previous = current_commit(root)
    files = sealed_files(root)

    lines = [
        COMMENT + " Policy seal over the gates, their library, the runner and the policy files.",
        COMMENT + " Generated by tooling/seal_policy.py from the globs it declares, so a new",
        COMMENT + " gate module cannot sit outside the seal while every hash still matches.",
        COMMENT + "",
        COMMENT + " Globs: " + ", ".join(SEALED_GLOBS),
        COMMENT + "",
    ]
    if note:
        # rstrip so a blank line in the note becomes "#" and not "# ":
        # git diff --check refuses trailing whitespace, and the last stage
        # of verification is exactly that check.
        lines.extend((COMMENT + " " + part).rstrip() for part in note.splitlines())
        lines.append(COMMENT + "")
    lines.extend([
        COMMENT + " python: " + ".".join(str(n) for n in sys.version_info[:3]),
        COMMENT + " date-utc: " + datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        COMMENT + " commit-previo: " + previous,
        COMMENT + " files: " + str(len(files)),
    ])
    lines.extend(digest(root / relative) + SEPARATOR + relative for relative in files)

    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("sealed %d files -> %s" % (len(files), SEAL_PATH.as_posix()))
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("action", nargs="?", default=CHECK, choices=(CHECK, WRITE))
    parser.add_argument(gate_io.PROJECT_ROOT_FLAG, default=".", type=Path)
    parser.add_argument("--note", default="", help="why the seal was reopened")
    args = parser.parse_args(argv)
    root = args.project_root.resolve()

    if args.action == WRITE:
        return write(root, args.note)

    reasons: list[str] = []
    if check(root, reasons):
        print("policy seal verified against " + SEAL_PATH.as_posix())
        return 0
    print("%s: %d problem(s)" % (DRIFT, len(reasons)), file=sys.stderr)
    for reason in reasons:
        print("  " + reason, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
